import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavHeaderWrapper from "@/components/NavHeaderWrapper/NavHeaderWrapper";
import Providers from "@/components/Provider/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const isAuthenticated = false;
  // const isGuestA = false;
  // const isGuest = dispatch()
  // const isGuestA = useSelector((state: RootState) => state.guest.isGuest);

  // const isGuestA = isGuest;
  // const pathname = usePathname();

  // Define pages that should not include the layout
  // const excludeLayoutPages = ["/register-login"];

  // const shouldExcludeLayout = excludeLayoutPages.includes(pathname);

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NavHeaderWrapper>{children}</NavHeaderWrapper>
        </Providers>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
